### ISSUE TITLE
The Things Uno and Node missing settings for EU868

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-devices#110]
#### Summary

The Things Uno is missing some settings that break routing when using ABP for EU868.

#### What is already there? What do you see now?

Device profile https://github.com/TheThingsNetwork/lorawan-devices/blob/master/vendor/the-things-products/the-things-uno-868.yaml that doesn't align with what the Arduino library does https://github.com/TheThingsNetwork/arduino-device-lib/blob/master/src/TheThingsNetwork.cpp#L701-L722

#### What is missing? What do you want to see? How do you propose to implement this?

I think this should be sufficient:

```yml
rx2DataRateIndex: 3
factoryPresetFrequencies: [867.1, 867.3, 867.5, 867.7, 867.9, 868.1, 868.3, 868.5]
```

but it needs testing.

**Comment by jpmeijers** [comment]
Something we need to check is if The Things Uno (like many other older AVR devices) resets its frame counters to 0 when it starts up.

**Comment by jpmeijers** [comment]
Yes, The Things Uno with the SendABP example from the Thing Network Arduino Library resets its frame counters when the board restarts. In the following screenshot I power cycled the board at 8:20:30.
![image](https://user-images.githubusercontent.com/948278/106560439-b3d6d000-652f-11eb-945a-37b47550d597.png)

The Things Uno is not the only device that behaves in this way. The most older devices (2015/2016) do not save the frame counters, and will start at 0 at startup or when the device restarts.

**Comment by benolayinka** [comment]
@rvolosatovs @adriansmares @elsalahy if you have an Uno can you test this? Seems like it should be sufficient to enter these parameters manually in TTS.

**Comment by Jaime-Trinidad** [comment]
I have been testing The Things Uno  using ABP and adding manually parameters, it doesn't present break routing, the only thing like this type of devices frame counter start in 0 everytime is reset.

**Comment by elsalahy** [comment]
@Jaime-Trinidad did the testing requested by @benolayinka.
Please assign me back if you need my assistance with something.

**Comment by Jaime-Trinidad** [comment]
Parameters were added manually, tests never present break routing. Using works fine:
rx2DataRateIndex: 3
factoryPresetFrequencies: [867.1, 867.3, 867.5, 867.7, 867.9, 868.1, 868.3, 868.5]

@htdvisser can we close this issue? do we need more test?

**Comment by htdvisser** [comment]
We'd still need to add those settings to https://github.com/TheThingsNetwork/lorawan-devices/blob/master/vendor/the-things-products/the-things-uno-868.yaml (and https://github.com/TheThingsNetwork/lorawan-devices/blob/master/vendor/the-things-products/the-things-node-868.yaml) before closing this issue.

**Comment by Jaime-Trinidad** [comment]
As ABP configuration we want it on DR? we have supportsJoin: true for OTAA in EU868 profile.

**Comment by Jaime-Trinidad** [comment]
ABP configuration for TTU is now in Device Repository #252 @htdvisser I close this issue.
