### ISSUE TITLE
Human readable schema errors

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-devices#13]
#### Summary

Schema validation errors could use a one-liner printing the error as human readable, i.e "Schema error in index.yml. Value 'example.com' of field 'website' is invalid."
Currently looks like:

./vendor/index.yaml is invalid
[
  {
    keyword: 'format',
    dataPath: '.vendors[0].website',
    schemaPath: '#/properties/website/format',
    params: { format: 'uri' },
    message: 'should match format "uri"'
  }
]

**Comment by johanstokking** [comment]
Closed by https://github.com/TheThingsNetwork/lorawan-devices/commit/5a4bf9a18e340996f815e586f4ccea5e6dad970a
