### ISSUE TITLE
Vendor specified JS decoder ignore or override or petition for inappropriate use for removal

### ISSUE THREAD

**Issue by descartes** [TheThingsNetwork/lorawan-devices#139]
#### Summary
Arduino MKR WAN 1310 has a JS decoder in the repository for a tutorial.

This appears in the background like a ghost entry that now has to be overridden.

The application shows None for the Uplink decoder. 

Saving as None doesn't turn off the decoder. Saving as Repository leaves it working. Changing to None still doesn't turn it off.

#### What do you see now?
Bizzare entries in the console log about an LED state that have nothing to do with the application, one very confused client on Zoom.

#### What do you want to see instead?
Nothing, zip, nada, zero, zilch - ie, no decoding unless I say so.

Strongly discourage generic devices having random JS put in to the device repository.

But for those times when there is a more use case appropriate for a JS decoder, some indication that one is present in the back-end that you weren't aware of and/or ability to copy it for editing at the application or device level 

#### How do you propose to implement this?
Not sure

#### Can you do this yourself and submit a Pull Request?
Hopefully @karlsoderby can address this issue related to the MKR WAN. I could do it but I hate to think how you'll audit a PR from a third party.

**Comment by nejraselimovic** [comment]
@neoaggelos can you tell something about this behavior?

**Comment by nejraselimovic** [comment]
Transferring this issue to `lorawan-stack` repository.
