### ISSUE TITLE
make validate fmt fails under Windows 10 Ubuntu Linux subsystem

### ISSUE THREAD

**Issue by xExecutioner** [TheThingsNetwork/lorawan-devices#145]
#### Summary

"make validate fmt" fails under Windows 10 with Ubuntu Linux subsystem. Did it on Windows 10 first by using WinGNU32 with the same error. Then switched to the Linux Subsystem feature, hoping it solves the problem which could be something about relative paths. Unfortunately same behaviour.

#### What do you see now?

`/mnt/d/TTI/lorawan-devices$ make validate fmt
npm run validate

> lorawan-devices@1.0.0 validate /mnt/d/TTI/lorawan-devices
> node bin/validate.js

vendor index: valid
comtac: valid index
comtac: lpn-td1: valid
comtac: lpn-td1: EU863-870: profile lpn-td1-profile-eu868 valid
comtac: lpn-km: valid
comtac: lpn-km: EU863-870: profile lpn-km-profile-eu868 valid
comtac: lpn-tsm: valid
comtac: lpn-tsm: EU863-870: profile lpn-tsm-profile-eu868 valid
comtac: lpn-td1: lpn-td1-foto.png image has correct extension
comtac: lpn-km: lpn-km-foto.png image has correct extension
comtac: lpn-tsm: lpn-tsm-foto.png image has correct extension
{ Error: Command failed: bin/validate-image ./vendor/comtac/lpn-km-foto.png
/bin/sh: 1: bin/validate-image: not found

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: 'bin/validate-image ./vendor/comtac/lpn-km-foto.png' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lorawan-devices@1.0.0 validate: `node bin/validate.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lorawan-devices@1.0.0 validate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxx/.npm/_logs/2021-04-28T06_02_52_508Z-debug.log
make: *** [Makefile:37: validate] Error 1`

#### What do you want to see instead?

Looks like the script bin/validate-image is called but it is not existing in the repo.

#### How do you propose to implement this?

Maybe the problem could also be on my side, but as I understand from the above output, this script is simply missing.

#### Can you do this yourself and submit a Pull Request?

No

**Comment by nejraselimovic** [comment]
@mjamescompton can you please take a look at this issue? If the problem is on not on the user side, please let us know if and when you can pick this up.

**Comment by Jaime-Trinidad** [comment]
which version of Go you have on WLS? I had the same problem and was the version you can upgrading this way https://sal.as/post/install-golan-on-wsl/

**Comment by xExecutioner** [comment]
> which version of Go you have on WLS? I had the same problem and was the version you can upgrade it this way: https://sal.as/post/install-golan-on-wsl/

Thanks @Jaime-Trinidad ,

**Comment by xExecutioner** [comment]
I was able to solve the problem by updating go to 1.16.3 by using the instruction of installing the newest binary distribution from @Jaime-Trinidad. Using apt-get installs an older version (1.13.8) which is not working! Thanks!
