### ISSUE TITLE
Define where to find vendorProfileID

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-devices#15]
#### Summary
in file <product-name>-profile.yaml, `vendorProfileID` field is required. We need to provide guidance in where partners can find this ID.

#### Why do we need this?
People don't know what this is or where to find it.

#### What is missing? What do you want to see?
A link or description

#### How do you propose to implement this?
Add a description

**Comment by laurensslats** [comment]
@johanstokking where can people find their `vendorProfileID` again? This is their LoRa Alliance ID right? I believe it corresponds to the list your posted [here](https://github.com/TheThingsNetwork/lorawan-devices/issues/5).

**Comment by johanstokking** [comment]
Here: https://lora-alliance.org/resource-hub/lora-alliance-vendor-id-qr-code

Please file a PR to add the instruction in https://github.com/TheThingsNetwork/lorawan-devices#vendor-index

**Comment by johanstokking** [comment]
I misread; your question is about the `vendorProfileID`. This can be freely issued by the vendor: the vendor can use their own numbers.

---

The `vendorID` is issued by the LoRa Alliance. The `vendor/index.yaml` is already updated. New vendors will be added by us. The vendor list is public: https://lora-alliance.org/resource-hub/lora-alliance-vendor-id-qr-code
