### ISSUE TITLE
How to add devices when the vendor does not have a Lora Alliance ID?

### ISSUE THREAD

**Issue by proffalken** [TheThingsNetwork/lorawan-devices#150]
#### Summary
Hi, I'm trying to add some devices from Elsys to make things easier to deploy, however they don't have a LoRa Alliance ID according to [the official list](https://lora-alliance.org/wp-content/uploads/2020/10/LoRa_Alliance_Vendor_ID_for_QR_Code.pdf)

Is there a "reserve code" that I can use?

#### What do you see now?
N/A

#### What do you want to see instead?
N/A

#### How do you propose to implement this?
N/A

#### Can you do this yourself and submit a Pull Request?
Yup, absolutely, I just need to know what I'm doing!

**Comment by TD-er** [comment]
There are other 'vendors' in the list which don't have a LoRa Alliance ID.
For example The Box Development doesn't mention an ID.

I just added a PR for my own project and I also don't have an alliance ID.

**Comment by Jaime-Trinidad** [comment]
@proffalken  as @TD-er   write, you can add them without LoRa Alliance ID.

**Comment by nejraselimovic** [comment]
@proffalken I will close this issue as your question seems to be answered by @TD-er and @Jaime-Trinidad, please reopen if necessary.

**Comment by proffalken** [comment]
@nejraselimovic - no need to reopen, but I would like to continue the conversation :)

@Jaime-Trinidad / @TD-er - do you just leave this value blank then? To me it looked like this value was compulsory rather than optional?

**Comment by TD-er** [comment]
Just a small part of the index.yaml file:
https://github.com/TheThingsNetwork/lorawan-devices/blob/71154d1e882bd99c35c8a6e4f57ee932d181f76c/vendor/index.yaml#L1564-L1583
When no ID is given, the key is also not mentioned.

**Comment by proffalken** [comment]
@TD-er perfect, thanks :)
