### ISSUE TITLE
Include Tektelic Agriculture Sensor

### ISSUE THREAD

**Issue by proffalken** [TheThingsNetwork/lorawan-devices#151]
#### Summary
At present, only the Kona indoor sensor is available for selection when provisioning a device.  It would be good to include the Agriculture Sensor as well

#### Why do we need this?
Increases the number of sensors available from Tektelic

#### What is already there? What do you see now?
Only the Kona generic sensor

#### What is missing? What do you want to see?
An option to select the Agriculture Sensor

#### How do you propose to implement this?
Add a new device profile

#### Can you do this yourself and submit a Pull Request?
Yes.

**Comment by nejraselimovic** [comment]
@proffalken thank you for contributing!
