### ISSUE TITLE
Configure the website on thethingsnetwork.org/device-repository

### ISSUE THREAD

**Issue by mjamescompton** [TheThingsNetwork/lorawan-devices#175]
#### Summary

Configure the lorawan devices website to be available from https://thethingsnetwork.org/device-repository

#### Why do we need this?

We do

#### What is already there? What do you see now?

Website running from default GitHub pages domain

https://thethingsnetwork.github.io/lorawan-devices/

#### What is missing? What do you want to see?

Configure the lorawan devices website to be available from https://thethingsnetwork.org/device-repository

#### How do you propose to implement this?

The website should work from the sub directory /device-repository

For this I made 2 env variables 

`BASE_PATH` and `BASE_URL` which are used by `.github/workflows/release.yml`, `website/webpack.config.js`  and `website/Makefile`

The correct configuration is as follows.

```
BASE_PATH ?= /device-repository
BASE_URL ?= https://thethingsnetwork.org
```

at the moment these are overwritten in `.github/workflows/release.yml` 

The website is self contained inside the `/website` directory, it has is own `Makefile` and `package.json` etc, please interface with these when making any changes that are need to make the website work. Check `/website/README.md` to run the site locally. It's basically a hugo website so should be setup similar to the docs. 

This should be enough to get you started let me know if you have any questions 

#### Can you do this yourself and submit a Pull Request?

@michalborkowski96 

For PR for files in the website i can review otherwise @johanstokking will need to review anything else.

**Comment by mjamescompton** [comment]
@michalborkowski96 Please wait to merge any changes until the team has confirmed that the website is ready to go live. I will update you here we are ready, though please create any needed PR's

**Comment by michalborkowski96** [comment]
Deployed, so closing
