### ISSUE TITLE
Command-line tools to create named device, profile and codec stubs

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-devices#18]
#### Summary

It would be convenient to have a `make new vendorId device` command that adds the device name to the vendor index and generates template files that will fail `make fmt validate`, so lazy users know what they need to edit.

#### Why do we need this?

Slightly easier to add devices

#### Can you do this yourself and submit a Pull Request?

@johanstokking

**Comment by johanstokking** [comment]
Indeed, having some basic CLI support would be useful.

**Comment by johanstokking** [comment]
@Jaime-Trinidad do you feel comfortable picking this up?

Would be nice to have a simple Node based CLI (https://www.npmjs.com/package/node-cli) that generates stubs for vendor, end device, profiles, codec definitions etc based on templates (something like https://www.npmjs.com/package/text-template).

**Comment by Jaime-Trinidad** [comment]
> @Jaime-Trinidad do you feel comfortable picking this up?
> 
> Would be nice to have a simple Node based CLI (https://www.npmjs.com/package/node-cli) that generates stubs for vendor, end device, profiles, codec definitions etc based on templates (something like https://www.npmjs.com/package/text-template).

@johanstokking Yes, I was thinking something like this will be usefull to device makers I work on it.

**Comment by Jaime-Trinidad** [comment]
@benolayinka @johanstokking I have been working on this V1, for the moment it download device templates, I am working on v.2 so information can be written on CLI and generate each template https://www.npmjs.com/package/devrepo-templates

**Comment by johanstokking** [comment]
Cool. Would be great if we can prompt a few things and fill them out.

Also why write the files under a `src` dir?

**Comment by Jaime-Trinidad** [comment]
Now it download and fill the template, I just update the version 2.1.4 https://www.npmjs.com/package/devrepo-templates

**Comment by johanstokking** [comment]
OK, so what is the plan with this? It's in your personal GitHub account now; we should either adopt it here, polish it up and make it part of the documentation flow, or keep it entirely separate.

**Comment by Jaime-Trinidad** [comment]
I'm making some changes, so device makers can clone the Github and use it, it create the templates so they can paste them in their folder, I will polish it and make it part of documentation, also move it to TTN Github.

**Comment by NicolasMrad** [comment]
any updates here?

**Comment by NicolasMrad** [comment]
@Jaime-Trinidad what are the updates here?

**Comment by johanstokking** [comment]
We're gonna do this differently.
