### ISSUE TITLE
Add device repository homepage

### ISSUE THREAD

**Issue by mjamescompton** [TheThingsNetwork/lorawan-devices#188]
#### Summary

Add a page that has an overview of most popular devices, vendors and tags. Featured vendors and an explanation of what can be found in the device repository. 

#### Why do we need this?

Making it easier to find devices you are looking for and improving SEO

#### What is already there? What do you see now?

The root page is identical to `/devices` which is redirected to the root. The root is just a list of all devices 

#### What is missing? What do you want to see?

The page should include, repository description, search, featured devices, featured tags, featured vendors, Link to all devices.

#### How do you propose to implement this?

Design by @pierrephz, @mjamescompton will build

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by KrishnaIyer** [comment]
This is covered by the partner portal: https://partners.thethingsindustries.com/devices
