### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by mjamescompton** [TheThingsNetwork/lorawan-devices#189]
#### Summary

Add a search bar to all pages.

#### Why do we need this?

Make it easier to find the device you are looking for.

#### What is already there? What do you see now?

A list of all devices.

#### What is missing? What do you want to see?

A search bar included on all pages. You should be able to search by device name.

#### How do you propose to implement this?

We already use Algolia for the docs so this could be easy to implement, otherwise research the best solution here, 
 https://gohugo.io/tools/search/#readout

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by KrishnaIyer** [comment]
This is covered by the partner portal: https://partners.thethingsindustries.com/devices
