### ISSUE TITLE
Support .png

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-devices#19]
#### Summary
Error message received when trying to use a .png file as the image of the sensor.

```
.photos.main should match pattern "\.(jpg|jpeg)$"
```

#### Why do we need this?
pngs are commonly used

#### What is already there? What do you see now?
support for jpg, jpeg

#### What is missing? What do you want to see?
support for pngs

#### How do you propose to implement this?
Add support for png in `https://lorawan-schema.org/draft/devices/1/schema#/definitions/endDevice`

#### Can you do this yourself and submit a Pull Request?
Need input from Johan, Ben

**Comment by laurensslats** [comment]
See: https://github.com/lorawan-schema/draft-devices/pull/4

**Comment by johanstokking** [comment]
Yeah I don't know. PNGs are for illustrations; photos are very inefficient with PNG.

They do support transparent backgrounds. Is that the use case specifically?

If it's just a photo, we should use JPG. The reason for this is responsiveness when serving (too large) images and keeping this repository a reasonable size. But for transparent backgrounds I get it.

**Comment by laurensslats** [comment]
Many manufacturers will provide PNGs because of the transparent background, or because this is simply what they have available. 

To save ourselves time in the future, we need to support this.

https://github.com/lorawan-schema/draft-devices/pull/4

**Comment by johanstokking** [comment]
OK fine!

Closed by https://github.com/lorawan-schema/draft-devices/pull/4
