### ISSUE TITLE
Improve vendor overview

### ISSUE THREAD

**Issue by mjamescompton** [TheThingsNetwork/lorawan-devices#190]
#### Summary

The vendor overview should show more information about the vendor.

#### Why do we need this?

Help user understand the vendor better and Improve SEO of these pages.

#### What is already there? What do you see now?

Vendor name, description if included, and list of devices.

#### What is missing? What do you want to see?

Vendor name, description, list of devices, social media links, website, vendor logo.

#### Can you do this yourself and submit a Pull Request?

yes, @pierrephz for design

**Comment by KrishnaIyer** [comment]
Covered by the partner portal https://partners.thethingsindustries.com/partners
