### ISSUE TITLE
Improve device list

### ISSUE THREAD

**Issue by mjamescompton** [TheThingsNetwork/lorawan-devices#192]
#### Summary

Improve design list layout and add new features.

#### Why do we need this?

Make it easier to find the device your looking for.

#### What is already there? What do you see now?

All devices.

#### What is missing? What do you want to see?

Some suggestions from discussions, larger width, smaller grid, no descriptions. Add filters by Sensors, IPCode, Frequency plans, LoRaWan version, regional parameters.

#### Can you do this yourself and submit a Pull Request?

yes, @pierrephz for design.

**Comment by KrishnaIyer** [comment]
This is mostly covered by the partner portal https://partners.thethingsindustries.com/devices
