### ISSUE TITLE
Device repository statistics API

### ISSUE THREAD

**Issue by pgalic96** [TheThingsNetwork/lorawan-devices#223]
#### Summary

An API endpoint to fetch statistics about device repo: number of end devices, number of end device profiles, most recent device profile uploads, etc.

#### Why do we need this?

To display device repository statistics

#### What is already there? What do you see now?

There are API endpoints for fetching devices.

#### What is missing? What do you want to see?

More general statistic API so we don't need to fetch the whole device list and deduce from there which device was uploaded recently etc.

#### How do you propose to implement this?

Just doing simple count queries, + some logic for storing the recent (or 5 most recent) uploads.

#### Can you do this yourself and submit a Pull Request?

Can review and test cc @johanstokking

**Comment by johanstokking** [comment]
We can generate a file with statistics as part of CI, and upload that to a public storage bucket.

Which statistics do you want exactly?

1. Total number of vendors
2. Total number of end devices
3. Total number of device profiles
4. Vendor + end device grouped per day?

**Comment by johanstokking** [comment]
It was for display on thethingsnetwork.org. I don't think this is super relevant for now.

We will be adding APIs to the Device Repository for export to new LoRa Alliance formats. While we're at it, we can make an API available with statistics. I'm gonna close this issue for now.
