### ISSUE TITLE
Remove GPS coordinates when there is no fix

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-devices#233]
#### Summary

Remove GPS coordinates when there is no fix.

cc @jamesl-dm

#### What do you see now?

The Oyster and Yabby codecs may return position values while these may be outdated.

Since The Things Stack Application Server from 3.13.3 is automatically publishing location solved events if the decoded payload contains coordinates, this may lead to unwanted side effects.

#### What do you want to see instead?

I don't want to see these position values in the fields that are used for valid values. Instead, I would put them under `cached`, and return a warning.

#### How do you propose to implement this?

Current codec: https://github.com/TheThingsNetwork/lorawan-devices/blob/9350955eefd9bd6468047b560ec540ce93575be8/vendor/digital-matter/oyster.js#L11-L24

Suggested change is to first check whether the fix failed. If that is the case, set the position values in a `cached` field and return a warning.

So the result would be:

```json
{
	"data": {
		"cached": {
			"latitudeDeg": 4.8684,
			"longitudeDeg": 52.34546,
			...
		},
		...
	},
	"warnings": ["fix failed"]
}
```

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by Jaime-Trinidad** [comment]
@johanstokking  as I understand in cached field only will be latitude and longitude, others in this case (Oyster) batV, speed..., will be outside this label right?

![Screen Shot 2021-07-14 at 16 22 36](https://user-images.githubusercontent.com/81958808/125638666-a116770e-fe2b-455a-8b4e-7d9d271d06b0.png)

**Comment by johanstokking** [comment]
Battery yes, speed probably not, as that also comes from GPS.

Best is to contact the manufacturer about what is up-to-date when there is no GPS fix.

**Comment by jamesl-dm** [comment]
That's right - latitude, longitude and speed come from the GPS.
ManDown comes from accelerometer only.

**Comment by Jaime-Trinidad** [comment]
I contact Digitalmatter, when fixFailed = true the following uses the most recent recorded data:
Latitude
Longitude
Speed
Heading

Regardless fixFailed status the following are always considered up to date:
InTrip
manDown
vBat

So the result must be:

{
	"data": {
		"cached": {
			"latitudeDeg": 4.8684,
			"longitudeDeg": 52.34546,
			"speedKmph": ...
                         "headingDeg": ...
		},
		"inTrip": false
                "batV": ...
                "manDown: false
	},
	"warnings": ["fix failed"]
}
