### ISSUE TITLE
Dragino LGT92 wrong longitude decoding 

### ISSUE THREAD

**Issue by Flo3561** [TheThingsNetwork/lorawan-devices#235]
#### Summary

Dragino LGT92 wrong longitude decoding 

#### What is already there? What do you see now?

Currently longitude payload is decoded as 0 if the MSB (most significant bit of the longitude packed bites) is 0 as well.
```
{
  "ALARM_status": "FALSE",
  "BatV": 3.713,
  "FW": 164,
  "LON": "ON",
  "MD": "Disable",
  "Pitch": 4.68,
  "Roll": 0.11,
  "altitude": 389.4,
  "hdop": 0.28,
  "latitude": 42.404444,
  "longitude": 0
}
```

#### What is missing? What do you want to see?

Longitude should be correctly decoded as for example the decoder here does: https://www.dragino.com/downloads/downloads/LGT_92/Decoder/LGT92-v1.6.4_decoder_TTN.txt

#### How do you propose to implement this?

...

#### Can you do this yourself and submit a Pull Request?

Could do a PR or review it but would strongly suggest the manufacturer @dragino does it.

**Comment by nejraselimovic** [comment]
@Flo3561 thanks for filing this issue! @dragino can you pick this up and fix the decoder function?

**Comment by nejraselimovic** [comment]
@Jaime-Trinidad I'm assigning you to take care of triaging this issue (assignee and milestone)

**Comment by Jaime-Trinidad** [comment]
@Flo3561 the same is in latitude both cases refer if the msb is 0 output is 0, I check with device maker so we can make changes on Dev Repo. Thanks

**Comment by Flo3561** [comment]
@Jaime-Trinidad: Yeah, that's true. Just didn't occured with my device. Thanks for your help.

**Comment by Jaime-Trinidad** [comment]
I make changes on latitude and longitude decoder, also verify now if msb of this parameters are 0 we still get values. #249
