### ISSUE TITLE
Added device does not show up in console as an option

### ISSUE THREAD

**Issue by tjvandam** [TheThingsNetwork/lorawan-devices#256]
#### Summary

...

#### What do you see now?

I have added a device to the repo called smart-parks, however it does not show op in the v3 console as a device option. Why is this? 

https://github.com/TheThingsNetwork/lorawan-devices/tree/master/vendor/smart-parks

#### What do you want to see instead?

I would expect that when a new device is added to the github repo, it should show up as a device option in the console. Maybe with a short delay. I can not find any information on how long this takes or if there are any additional steps to take.

#### How do you propose to implement this?

Devices accepted and added to the github repo should show up as a device option in the console within a few hours. 

#### Can you do this yourself and submit a Pull Request?

I am not sure why this is not happening, so no idea where to start fixing it.

**Comment by rroemhild** [comment]
It will be included with the next TTS release.

**Comment by Jaime-Trinidad** [comment]
Hi @rroemhild as @rroemhild wrote they will be included with the next TTS release, there is nothing to fix for the moment.

**Comment by Jaime-Trinidad** [comment]
@tjvandam smart-park devices already can be added on TTS console.

<img width="911" alt="Screen Shot 2021-07-27 at 13 02 36" src="https://user-images.githubusercontent.com/81958808/127143411-ab0f1c90-5f11-4a98-ae43-e330d97f97c6.png">
