### ISSUE TITLE
Improve Device repo WSL installation guide documentation

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-devices#276]
#### Summary
Users are facing issues working with WSL installation in the Device Repository while following the instructions here. https://github.com/TheThingsNetwork/lorawan-devices#prerequisites
#### Why do we need this?
To add devices to the Device Repository via Windows platforms.
#### What is already there? What do you see now?
Users are facing issues with node, npm, and go installation in WSL by following the below instructions.
https://github.com/TheThingsNetwork/lorawan-devices#prerequisites
#### What is missing? What do you want to see?
Device Repository Installation guide for Windows Users with node, npm and go installation instructions.
#### How do you propose to document this?
**Device Repository Installation guide for Windows Users:**
**Step 1:** Install Windows Subsystem for Linux here. https://docs.microsoft.com/en-us/windows/wsl/install-win10
**Step 2:** To use Device repository, below development dependencies should be installed. Check your Node.js, npm and Go versions:

- Node.js version 14.x
- npm version 6.x
- Go version 1.15.x

```
$ node -v
$ npm -v
$ go version
```
**Step 2a:** Install npm and node, execute the below commands.
```
$ sudo apt-get --purge remove node
$ sudo apt-get --purge remove nodejs
$ curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
$ sudo apt-get install -y nodejs
$ sudo apt-get install gcc g++ make
```
 **Step 2b:** Install go, download Go for Linux here. https://golang.org/doc/install and  execute the below commands
```
$ sudo rm -rf /usr/local/go                                                                                                                                                                                         
$ sudo tar -C /usr/local -xzf /path/to/go1.16.5.linux-amd64.tar.gz                                                                                                    
$ export GOROOT=/usr/local/go                                                                                                                                                                                       
$ export GOPATH=$HOME/go                                                                                                                                                                                            
$ export PATH=$GOPATH/bin:$GOROOT/bin:$PATH 
```
**Note:** Before running the `sudo tar -C /usr/local -xzf /path/to/go1.16.5.linux-amd64.tar.gz` command, make sure to replace the `/path/to/` to the file downloaded directory.

**Step 2c:** Now, to check your Node.js, npm and Go versions:
```
$ node -v
$ npm -v
$ go version
```
**Step 3:** To help you add devices to the device repository, you can follow along in this example video where we walk through all of the instructions below. https://www.youtube.com/watch?v=pnwtEgw4f-c
**Step 4:** Add your devices and make the changes accordingly to the device repository.
**Step 5:** Execute below commands to validate the changes before raising a Pull Request.
```
$ make deps
$ make validate fmt
$ make validate
```
#### Can you do this yourself and submit a Pull Request?
No. @benolayinka

**Comment by Jaime-Trinidad** [comment]
@bafonins and @NicolasMrad  I already deploy a WSL installation guide when I started because I notice the problem with Windows, the suggestion of @johanstokking was to make it shorter as it is now, let me search, reopen that PR and edit it, to so you can review it.

**Comment by NicolasMrad** [comment]
what's the status here?

**Comment by Jaime-Trinidad** [comment]
@NicolasMrad can you take a look to #422 last year we also discuss this topic that is not necessary to add all the guide, to close the issue and the PR

**Comment by NicolasMrad** [comment]
if it looks good for you then it's good for me

**Comment by NicolasMrad** [comment]
@Jaime-Trinidad any updates?

**Comment by Jaime-Trinidad** [comment]
It has been a while and I have not got any mail, from device makers having problems working with windows, I will close this issue.
