### ISSUE TITLE
RX2 frequency incorrect in (almost) all vendor templates

### ISSUE THREAD

**Issue by TD-er** [TheThingsNetwork/lorawan-devices#288]
I noticed a problem with my nodes when using ABP.
I am using nodes with the RN2483 modules, so that should be using a compliant stack.

What I observed was that the gateway sends a downlink message on every uplink message.
But the downlink counter does not increment on the node.

Found [this issue](https://www.thethingsnetwork.org/forum/t/stack-v3-sends-unrequested-downlink-data-for-new-abp-device/48327) where descartes suggested to check the frequencies.

The downlink message suggests this:

> Rx1 Delay  5
> Rx1 Data Rate Index  5
> Rx1 Frequency  868500000
> Rx2 Frequency  868525000

but my code (and all example code):
```c++
// RX window 2
set2ndRecvWindow(3, 869525000);
```

[LoRaWAN Regional Parameters](https://net868.ru/assets/pdf/LoRaWAN-Regional-Parameters-v1.1rA.PDF) suggests that 869.525 MHz is the right frequency for RX2.
But the template in the Readme.md for a vendor template states 868.525 MHz (committed by @johanstokking roughly 7 months ago)
So all vendor specific templates now state this frequency (one or two use the correct 869.525 MHz)

I tried to alter this RX2 frequency in my device settings, but I could not get it to activate.
Jac Kersing told me I had to reset the session of my devices via the command line tool, but I was not able to get this tool to log me in (worth maybe another issue) even though I did try lots and lots of things for over an hour.

To summarize the impossible decision to be made, since each fix is a bad one and leaving it like this is even worse.

- Either force fix all templates and all stored device settings to use the 869.525 MHz for EU based nodes using ABP. This may render those nodes that were configured on the node to use 868,525 MHz unable to receive RX2 messages. But at least the official frequency for this will be used as the current one is not allowed to send at this TX power and air time.
- Leave it as it is now, where gateways now are sending downlink messages way more often than desired.
- Make a "compromise"  where current settings will remain if nodes were set to the wrong frequency and update all other settings + templates.

And above all, please add a button on the console to reset a session for a device, as for now it seems to be impossible for Windows users to login using the command line tool if you're not using Edge as a default browser, or maybe once have set some host names for the command line tool to be localhost.
When trying to login, no browser is opened, only the Windows store to find an application for which it does not even add a suggestion making it impossible to continue without a lot of ctrl-C pressing, cursing and really starting to doubt oneself.

**Comment by Jaime-Trinidad** [comment]
Hi @TD-er I will change example template info, so ABP devices submitted don't present any problem, for the moment there is only one ABP device in the repository. All the join devices are not affected by this.

**Comment by Jaime-Trinidad** [comment]
Changes are done and they are now in the device repository.

**Comment by TD-er** [comment]
How can I change the created devices which were based on an incorrect template?
I can update it in the settings, but this does not seem to be updated in the backend.
Do I need to recreate those devices? (and thus loose their End Device ID)

**Comment by Jaime-Trinidad** [comment]
@TD-er this PR still are draft because we are working on it, it isn't deploy yet, in the actual version RX2 now is correct for all devices but this don't affect them as 99% use join activation, only The Things Uno board has ABP connection and is already fixed, in the console this will be in the next release, but you can work with the repository.

**Comment by Jaime-Trinidad** [comment]
Also which devices are affected so I can look at them @TD-er .

**Comment by TD-er** [comment]
Not sure if you can see it for my nodes.

For example this one:
![image](https://user-images.githubusercontent.com/3751318/132412420-09e3d368-68fb-491e-85a3-068d5aac90e8.png)

When I made this issue, I could change the RX2 frequency in the web interface in the Advanced MAC settings:
![image](https://user-images.githubusercontent.com/3751318/132412544-49baf33f-b2a5-48ef-9b6d-747a9635a911.png)

But changing it, did not change the behavior, just like it wasn't processed in the backend.
I then made a new device, for testing, with the RX2 frequency set to the right frequency.
That node did work properly (with ABP of course, as that's where it makes sense to set the RX2 parameters) without the gateway sending a downlink for every uplink.

Right now, I cannot access these nodes to test, as they are roughly 1100 km away in Delsbo, Sweden and I'm in the Netherlands.
They also are not turned on right now.
