### ISSUE TITLE
smart-parks device no longer available as an option in TTN

### ISSUE THREAD

**Issue by tjvandam** [TheThingsNetwork/lorawan-devices#297]
#### Summary
Somehow the smart-parks devices are no longer available as an option in TTN. 

...

#### What do you see now?
This did work for a while, but today I tried to add a new device and could not select smart-parks as a brand.

...

#### What do you want to see instead?
I would like to see smart-parks devices again (there is only 1 at the moment)
...

#### How do you propose to implement this?
Not sure why this is happening.

...

#### Can you do this yourself and submit a Pull Request?
Do not know where these issue is.

...

**Comment by htdvisser** [comment]
It looks like `smart-parks` and `nexelec` were accidentally removed from the vendor index in https://github.com/TheThingsNetwork/lorawan-devices/pull/242.

@Jaime-Trinidad can you restore these?

**Comment by Jaime-Trinidad** [comment]
> It looks like `smart-parks` and `nexelec` were accidentally removed from the vendor index in #242.
> 
> @Jaime-Trinidad can you restore these?

Yes, in the vendor index were deleted, the are already restored, @tjvandam in the next release you will see smart park devices again.

**Comment by tjvandam** [comment]
We need to update the decoder on this device also, so that will then also be in the next release. Thanks for the quick update on this.

**Comment by Jaime-Trinidad** [comment]
@tjvandam in next release smart park devices will be again in the console, fixes are already done and merged, I close this issue.
