### ISSUE TITLE
missing or broken links

### ISSUE THREAD

**Issue by iulia-branescu** [TheThingsNetwork/lorawan-devices#302]
#### Summary

There are some broken or missing links for the 'Partner webpage' buttons in the repo: https://www.thethingsnetwork.org/device-repository/devices/tektelic/t00048xx-smart-room-pir/ + https://tektelic.com/public/catalog/smart-room-base-sensor + https://www.thethingsnetwork.org/device-repository/devices/sensative/strips/

**Comment by Jaime-Trinidad** [comment]
links are fixed and merged.
