### ISSUE TITLE
Add reviewer guides

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-devices#33]
#### Summary

Add guides for reviewers

#### Why do we need this?

For community reviewers to have clear guidelines that they can apply when reviewing pull requests from the device maker community.

#### What is already there? What do you see now?

Contributing guidelines

#### What is missing? What do you want to see?

Guidelines on what to check, suggesting:

- Validation must pass (CI already does this)
- Payload codecs are provided with examples
- The Javascript code is clean
- When adding or changing vendors: check that the information is correct, especially the vendor ID and OUIs
- When adding or changing end devices: check that the LoRaWAN certification is correct

#### How do you propose to implement this?

- Add checkboxes to pull request template, so the contributor has a set of things to check first
- Add a list of requirements to the existing documentation

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by NicolasMrad** [comment]
Is this still relevant? If so, how can we move forward?

**Comment by johanstokking** [comment]
We probably don't need this anymore.
