### ISSUE TITLE
LGT-92 Decoder: IF query in Kiel Germany causes permanent longitude=0

### ISSUE THREAD

**Issue by marcusgrtz** [TheThingsNetwork/lorawan-devices#331]
https://github.com/TheThingsNetwork/lorawan-devices/blob/277719e49c730b5d71fd1b7d0b2a5497911d6093/vendor/dragino/lgt92.js#L17-L19

IF query in Kiel Germany causes permanent longitude=0

**Comment by Flo3561** [comment]
It looks like this PR here hasn't mad it into the master...
https://github.com/TheThingsNetwork/lorawan-devices/pull/249

**Comment by NicolasMrad** [comment]
@Jaime-Trinidad any progress here

**Comment by Jaime-Trinidad** [comment]
@NicolasMrad there is a good solution for this problem #362 but it can't be merge as the CLA won't be signed, I will search for other solutions.

**Comment by Jaime-Trinidad** [comment]
The problem must be solved with #438 the decoder file will be updated in the next release, after that if trouble continues, please reopen this issue.
