### ISSUE TITLE
Support other Firmware versions for Dragino LGT92 decoding

### ISSUE THREAD

**Issue by Flo3561** [TheThingsNetwork/lorawan-devices#347]
#### Summary

Support other Firmware versions for Dragino LGT92 decoding

#### What do you see now?

I currently get the following error from the cloud console `firmware version 1.6.4 for model dragino/lgt92 not found`

#### What do you want to see instead?

I would like to see support for all the firmware versions 1.6.x => see here a link: [Firmware versions](https://www.dragino.com/downloads/downloads/LGT_92/firmware/changelog.txt)

#### How do you propose to implement this?

...

#### Can you do this yourself and submit a Pull Request?

Could do a PR or review it but would strongly suggest the manufacturer @dragino does it.

**Comment by Flo3561** [comment]
The same probably goes also for other sensors like:
- LHT65 https://www.dragino.com/downloads/downloads/LHT65/Firmware/ChangeLog
- LDDS20 https://www.dragino.com/downloads/downloads/LoRa_End_Node/LDDS20/Firmware/Readme.txt
- LDS01 https://www.dragino.com/downloads/downloads/LoRa_End_Node/LDS01/Firmware/ChangeLog.txt
- LSN50v2-D20 https://www.dragino.com/downloads/downloads/LoRa_End_Node/LSN50v2-D20/Firmware/changelog
- LSN50v2-S31 https://www.dragino.com/downloads/downloads/LoRa_End_Node/LSN50v2-S31/Firmware/Changelog

**Comment by Flo3561** [comment]
Hi @Jaime-Trinidad,
Please find here in the following screenshot my error I get in the console:
![image](https://user-images.githubusercontent.com/25773748/142726419-ba297d4a-190a-4fbe-b298-eef5e73cbc5a.png)

And here is the data event detail from the decoding uplink data:
```
"data": {
    "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
    "namespace": "pkg/devicerepository/store/remote",
    "name": "firmware_version_not_found",
    "message_format": "firmware version `{firmware_version}` for model `{brand_id}/{model_id}` not found",
    "attributes": {
      "brand_id": "dragino",
      "firmware_version": "1.6.4",
      "model_id": "lgt92"
    },
    "correlation_id": "6e8440c390104fc0ad645f3338af9321",
    "code": 5
  }
```

**Comment by NicolasMrad** [comment]
@Jaime-Trinidad any progress here?
