### ISSUE TITLE
Add virtual wall of fame tag

### ISSUE THREAD

**Issue by mjamescompton** [TheThingsNetwork/lorawan-devices#351]
#### Summary

For conference 2022 we want to be able to filter by virtual wall of fame

#### Why do we need this?

We need a link to all the wall of fame devices

#### What is already there? What do you see now?

There are tags

#### What is missing? What do you want to see?

Add tag landing page call virtual wall of fame.

#### How do you propose to implement this?

Add wall of fame tag to devices or add a custom filter list as part of the website only

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by NicolasMrad** [comment]
since this is created some time ago, is it still relevant?

**Comment by mjamescompton** [comment]
Speak to ionela about her expectations for the digital wall of fame. During the last conference the digital wall of fame was the entire device repository, if people are paying to be apart of the wall of fame we could show only these products somewhere online
