### ISSUE TITLE
Elsys not showing up in the brands list

### ISSUE THREAD

**Issue by efpage** [TheThingsNetwork/lorawan-devices#359]
Adding some new devices on TTN, I found that ELSYS ist not showing up in the brands list for end devices. Surely Elsys is in the repository lorawan-devices/vendor/, so maybe anybody can check, why it is not selectable?

BR, Eckehard

**Comment by Jaime-Trinidad** [comment]
Hi @efpage let us check why you can't select it, Elsys as you wrote are in the device repository.

**Comment by efpage** [comment]
Hy Jaime,

this is what I get on the V3 console:

I would expect Elsys somewhere in this list, but it is not there, even 
not at any other position.

There is also another error (?) in the console. I can manually register 
one device, this works fine. But if I select to add another device right 
after (which is a very handy option), the register end device button 
does not work. So I get stuck in this menue. Maybe this is also worth a 
look. I´m running chrome latest version.

Best regards,

Eckehard


Am 14.12.2021 um 10:25 schrieb Jaime Trinidad:

**Comment by Jaime-Trinidad** [comment]
Hi @efpage next release must deploy the name elsys, for the moment is not an error only in console is the company name ElektronikSystem, take a look to it, their devices are there, but the changes are already done to deploy the name Elsys
