### ISSUE TITLE
Apply LoRaWAN brand guidelines

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/lorawan-devices#372]
#### Summary

Apply LoRaWAN brand guidelines

#### Why do we need this?

Comply with LoRa Alliance band guidelines for using LoRaWAN and the LoRa Alliance logo.

#### What is already there? What do you see now?

Concerning page: https://www.thethingsnetwork.org/device-repository

- First use of LoRaWAN does not carry (R)
- Wrong LoRa Alliance logo used in the bottom

#### What is missing? What do you want to see?

- Add (R) to first LoRaWAN usage, so "Device Repository for LoRaWAN®"
- Use correct logo, one of these:

![Alliance_horizontal_member_RGB_color-01](https://user-images.githubusercontent.com/13334001/150806955-84234e3d-ff85-4f00-aa66-86b252ba1f24.png)
![Alliance_vert_member_RGB_color-01](https://user-images.githubusercontent.com/13334001/150806965-b4bb3503-a825-4f82-abd5-46f47f846fe7.png)

#### How do you propose to implement this?

I suppose very minor layout changes

#### Can you do this yourself and submit a Pull Request?

Can review

**Comment by johanstokking** [comment]
Updated comment based on discussions with Alliance. This is now good to go.

**Comment by mjamescompton** [comment]
@pierrephz Something for you to be aware of when designing the websites.

**Comment by NicolasMrad** [comment]
Is there sill work to be done here?
