### ISSUE TITLE
nke Watteco ModBus codec

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/lorawan-devices#424]
#### Summary

@Watteco @Jaime-Trinidad 
The codec for the nke Watteco ModBus device is missing from this repo under https://github.com/TheThingsNetwork/lorawan-devices/tree/master/vendor/nke-watteco

#### Why do we need this?

Support nke Watteco ModBus devices.

#### What is already there? What do you see now?

Many of the other nke Watteco devices are already included, but the ModBus device is missing.

#### What is missing? What do you want to see?

ModBus

#### How do you propose to implement this?

...

#### Can you do this yourself and submit a Pull Request?

The vendor should rather do it.

**Comment by Jaime-Trinidad** [comment]
I already contacted NKE-Watteco so they can add their `ModBus` devices

**Comment by Jaime-Trinidad** [comment]
@Watteco any update for adding `ModBus` to the Repository?

**Comment by Jaime-Trinidad** [comment]
Hi @jpmeijers @Watteco already add a ModBus in the repository please take a look at #458 I will close this issue if there is something else needed please feel free to open it.
