### ISSUE TITLE
Simplify device repo

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-devices#5]
#### Summary
As of now, its too complicated and error-prone. 

No. | Remove | Why
---|---|---
1 | Operating temperature | we're not copy-pasting datasheets
2 |RelativeHumidity | we're not copy-pasting datasheets
3 |Compliancy | we're not copy-pasting datasheets 

No. | Issues | Why
---|---|---
1 | Not everyone will install the validation tools | Lot of hassle to install
2 | yaml thing doesn't work well | it barely gives input (or I didn't install correctly). Either way, it needs improvements
3 | Not clear what to enter | list all options clearly as descriptions 
4 | HW version | not clear
5 | SF version | not clear
6 | firmwareVersions version or numeric | choose 1, chis confuses ppl
7 | Firmware Version profiles are most of the times similar | EU863-870 & AS923 may refer to the same file (might not be an issue)
8 | vendorProfileID | what is it and how to get it
9 | pen & oui | what is it, where to find it. Why is it necessary?

#### What is missing? What do you want to see?
- [ ] Improve CONTRIBUTING.md
- [ ] Clear example with all options people can fill out
- [ ] Clarify required and optional fields
- [ ] Not an option to have HW & SF version as we have it now. Reconsider this part

#### How do you propose to implement this?
I will work on documentation. Johan to provide feedback

#### Can you do this yourself and submit a Pull Request?
Yes, with input from @johanstokking

**Comment by johanstokking** [comment]
> 1	Operating temperature	we're not copy-pasting datasheets
> 2	RelativeHumidity	we're not copy-pasting datasheets
> 3	Compliancy	we're not copy-pasting datasheets

I think we should keep them for three reasons:
1. They are optional
2. They are useful to feed a device catalog / marketplace
3. They will not be copy-pasted by us, but by device makers. It is in their best interest to provide as much information as possible in a structured way

> 1	Not everyone will install the validation tools	Lot of hassle to install

This is literally one command: `npm install`, with Node installed. Also, it is [the most popular](https://githut.info/) language. This is not going to be easier.

Also, this is optional. Everything will get validated by GitHub for pull requests.

> 2	yaml thing doesn't work well	it barely gives input (or I didn't install correctly). Either way, it needs improvements

What do you mean with "barely"? 

<img width="584" alt="Screenshot 2020-06-24 at 13 52 59" src="https://user-images.githubusercontent.com/13334001/85551190-0a873d80-b622-11ea-93b2-32988a065b06.png">

The instructions for VS Code is already there.

Sure, it would be great if we can have an interactive web interface, but that's a project in itself.

> 3	Not clear what to enter	list all options clearly as descriptions

See above; your editor will show that.

Just create a template with all fields, options, examples and comments.

> 4	HW version	not clear
> 5	SF version	not clear

What is not clear about this?

See for example: https://www.bosch-connectivity.com/products/connected-mobility/parking-lot-sensor/downloads/

It is very common to have multiple versions of hardware and software, which are or are not certified and work or do not work in certain regions. As you see with the parking sensor, the payload format changed, so the profile changed. We don't want to show these iterations as different devices.

> 6	firmwareVersions version or numeric	choose 1, chis confuses ppl

We need a numeric field for the LoRaWAN Firmware Management specification. It's an optional field anyway.

> 7	Firmware Version profiles are most of the times similar	EU863-870 & AS923 may refer to the same file (might not be an issue)

You can use the same profile for multiple versions and for multiple regions indeed, if they are the same.

> 8	vendorProfileID	what is it and how to get it

It's 

> 9	pen & oui	what is it, where to find it. Why is it necessary?

They are not necessary.

See field descriptions what they are. For example:

<img width="549" alt="Screenshot 2020-06-24 at 14 07 13" src="https://user-images.githubusercontent.com/13334001/85553209-06f4b600-b624-11ea-844d-b5626d6ae5bb.png">

They are useful for linking to vendor information. The OUI is also typically used to issue DevEUIs, so we can recognize device vendors this way.

> #### What is missing? What do you want to see?
> * [ ]  Improve CONTRIBUTING.md
> * [ ]  Clear example with all options people can fill out
> * [ ]  Clarify required and optional fields

I agree

> * [ ]  Not an option to have HW & SF version as we have it now. Reconsider this part

What is the proposal?

**Comment by johanstokking** [comment]
VendorID | Name
--- | ---
1 | 1M2M
2 | 2j, L.t.d.
3 | 3S
4 | Bureau Veritas Consumer Products   Services, Inc.
5 | A2A Smart City S.p.A.
6 | AAEON Technology Inc.
7 | Abeeway
8 | Abel Delft B.V.
9 | ABENERGIE SpA
10 | ABINC - Associa
11 | ACCESS CO., LTD.
12 | ACKLIO
13 | AcSiP Technology Corp.
14 | ACTILITY SA
15 | Adaptive Modules Limited
16 | Adeunis
17 | ADRAL Alentejo Regional   Development Agency
18 | Advantech Co., Ltd.
19 | ADVEEZ SAS
20 | Aexonis
21 | Afnic
22 | Airgain, Inc.
23 | AISenz Inc.
24 | AIUT Sp. z o.o.
25 | Alflex Technologies
26 | Alibaba (China) Co., Ltd
27 | Allion Labs, Inc.
28 | ALPITEL SPA
29 | Alternative Energy Technologies
30 | Amateur Radio Safety Foundation   Inc. ARSFI
31 | American Tower
32 | American University of Beirut
33 | AMIHO Technology Ltd.
34 | Andrea Informatique
35 | Anglia Components
36 | Antenna Hungaria Co.
37 | Anylink Systems AG
38 | APANA
39 | Appropolis Inc
40 | Arabian Internet and   Communications Services Company
41 | Arad Technologies
42 | Aragon Institute of Engineering   Research
43 | Arcade Solutions AG
44 | ARCHOS SA
45 | Arkessa limited
46 | ARM Cloud Services Limited
47 | ARTERIA
48 | Asic North, Inc.
49 | ATAL Technologies Limited
50 | ATIM
51 | AUTHENTIC DATA CO., LTD
52 | Automagi Inc.
53 | Avalanche Float Solutions GmbH
54 | Averos FZCO
55 | Avnet Europe Comm. VA
56 | AXATEL SRL
57 | AXIANS
58 | Axino Solutions AG
59 | BAYLAN OLCU ALETLERI SAN. TIC.   LTD. STI.
60 | bcom
61 | Beijing GTI IoT Technology   Corp., Ltd.
62 | Beijing Manthink Technology   Co.Ltd
63 | Beijing Sensoro Technology Co.   Ltd.
64 | Bern University of Applied   Science
65 | BH TECHNOLOGIES
66 | Birdz
67 | BLAZING ENERGY Co., Ltd
68 | Netmore
69 | Robert Bosch GmbH
70 | Bouygues Telecom
71 | Braveridge Co., Ltd.
72 | CableLabs
73 | Cambium Networks
74 | CardiffSchools.Net
75 | Carnegie Technologies, LLC
76 | CAT Telecom PCL
77 | CEAC INTERNATIONAL LIMITED
78 | CENSIS-University of Glasgow
79 | Centrale-Sup
80 | Ceske Radiokomunikace, a.s.
81 | Charter Communications
82 | ChengDu Boost Information   Technology
83 | Chengdu EasyCred IoE Systems   Tech. Ltd. Co
84 | Chengdu Qinchuan Technology   Development
85 | Circuit Design, Inc.
86 | Cisco Systems, Inc
87 | Citykinect
88 | CNIT - National Inter-University   for Telecommunications
89 | Cognosos, Inc.
90 | Coheros Oy
91 | Combain Mobile AB
92 | MachineQ, a Comcast Company
93 | Comfone AG
94 | Comms365 Limited
95 | CommuniThings SA
96 | Computer Network Information   Center Chinese Academy of Sciences
97 | Computing Systems, Security and   Networks (CSSN) Research Lab
98 | comtac AG
99 | conbee GmbH
100 | Connexin Ltd
101 | Connit SAS
102 | Conny Tech Pte. Ltd.
103 | Contela, Inc.
104 | Coris E.C.S.
105 | CRESITT Industrie
106 | CSEM
107 | Daliworks
108 | DB Station&Service AG
109 | Decentlab GmbH
110 | Definium Technologies, Pty Ltd.
111 | DEKRA Testing and Certification,   S.A.U.
112 | Dept. of Security Technologies   and Engineering, FD CVUT in Prague
113 | Diehl Metering SAS
114 | Digi International
115 | digimondo GmbH
116 | Digita Oy
117 | Digital Catapult
118 | Digital Matter Pty Ltd
119 | Digital Nordix AB
120 | Dimosystems BV
121 | DMIC
122 | DREAMLINE
123 | E-PEAS S.A.
124 | EASEL Inc.
125 | EasyLinkin Co.,LTD.
126 | EasyReach Solutions Pvt. Ltd.
127 | Econocom France SAS
128 | Eddy Home Inc.
129 | EDF
130 | Edinburgh Napier University
131 | Electronics and   Telecommunications Research Institute
132 | ElektronikSystem i Ume
133 | eleven-x
134 | Elitegroup Computer Systems CO.,   LTD.
135 | ELMEC INFORMATICA SPA
136 | Elster Water Metering SAS
137 | Emaga Interconnect Technologies   Co., Ltd.
138 | Embit srl
139 | Eniga Technology AB
140 | Enkom Inventis AG
141 | ENTEGA AG
142 | ER-Telecom
143 | ETA2U SRL
144 | Ethertronics inc
145 | Etteplan
146 | Eurofins Digital Testing Belgium   NV
147 | EUROTECH
148 | Everynet BV
149 | EWATTCH
150 | eWBM Co., Ltd.
151 | EXPEMB
152 | FactoryLab BV
153 | Facultad Regional Delta -   Universidad Tecnologica Nacional
154 | FAIRWAYiQ, Inc.
155 | FastNet
156 | Fermat Software LLC
157 | ffly4u
158 | Fleet Space Technologies Pty Ltd
159 | Flex Automotive Gmbh
160 | Flexworks limited
161 | Focalcrest Inc
162 | Forest Industries Research   Centre - University of the Sunshine Coast
163 | Foxconn Global Network   Corporation
164 | Freestyle Technology Pty Ltd
165 | Front Porch, Inc.
166 | Fujitsu Component Limited
167 | Gemalto SA
168 | Gemtek Technology Co., Ltd.
169 | GETRALINE
170 | Giesecke & Devrient GmbH
171 | GIMASI SA
172 | Gizero Energie Srl
173 | GlobalSat WORLDCOM GROUP
174 | GREEN HOUSE CO., LTD.
175 | GreenWaves Technologies
176 | Grupo Sabio, SA de CV
177 | Guangdong DAPU Telecom   Technology Co.
178 | Guangzhou Robustel Technologies   Co., Ltd
179 | GWF MessSysteme AG
180 | H2O Degree
181 | habemus! electronic + transfer   GmbH
182 | Hangzhou Lowan Information   Technology Co.
183 | Hangzhou Thingcom Information   Technology Co.,Ltd
184 | Haxiot
185 | Helium Systems Inc
186 | Hexing Electrical Co., Ltd.
187 | hl2
188 | Holley Technology Ltd.
189 | hoopo systems Ltd.
190 | House of Invention Int'l (HOI)
191 | Hub One
192 | Humax USA, Inc.
193 | IBM Research GmbH
194 | ICT Faculty
195 | IDEMIA SA
196 | IEM SA
197 | iioote AB
198 | iMinds VZW
199 | IMST GmbH
200 | Inmarsat
201 | Inovonics
202 | Institute for Information -   Smart Network System Institute-Advanced Mobile Communications System
203 | Institute of High Technologies   of Belgorod State University
204 | Instituto Baikal
205 | Intelligent Interaction
206 | INTERCOMP S.p.A.
207 | Interpolation Co.,Ltd.
208 | Invenit B.V.
209 | Invisible Systems Ltd
210 | Invitech Megoldasok Zrt.
211 | INVOXIA
212 | Last Mile Solutions AS
213 | IOT WATER ANALITYCS, S.L.
214 | QuaeNet Inc.
215 | IP-Only Networks AB
216 | Iris Technologies Inc.
217 | Itron, Inc.
218 | IVU Softwareentwicklung GmbH
219 | Jaguar  de Mexico, SA de CV
220 | JRI
221 | Kaunas University of Technology
222 | KELLER AG fur Druckmesstechnik
223 | KERLINK
224 | Kiwi Technology Inc.
225 | Kolff Computer Supplies b.v.
226 | Kolmostar
227 | Konica Minolta Business   Solutions Europe
228 | Kontron Modular Computers
229 | Korea Institute of Science and   Technology Information (KISTI)
230 | KotahiNet
231 | KPN
232 | KU Leuven
233 | La Poste
234 | Lacuna Space Ltd.
235 | Laird Connectivity, Inc.
236 | Lapp Automaatio
237 | Lartech LLC
238 | Lat-Lon, LLC
239 | Legeniot Co., Ltd.
240 | Legrand
241 | Levikom Eesti OU
242 | Lierda Science & Technology   Group Co., Ltd
243 | Lineable Inc
244 | Lite-On Technology Corp.
245 | LM Ingenierie
246 | LORIOT.io
247 | LOSTnFOUND AG
248 | Lucy Zodion
249 | Luxembourg Online SA
250 | Lyngsoe Systems Ltd
251 | Lyse AS
252 | M2B Communications Inc.
253 | Machines Talk
254 | Macnica, Inc
255 | Maddalena S.p.A.
256 | Magnitude Space B.V.
257 | Maxiiot Limited
258 | MCCI Corporation
259 | MCF88 SRL
260 | MEAS FRANCE
261 | Menowatt Ge S.p.A.
262 | Mesh Systems
263 | Meshed Pty Ltd
264 | Meshify
265 | Metova, Inc.
266 | Microchip Technology
267 | Microshare Inc
268 | Microtronics Engineering GmbH
269 | Milandr, Inc.
270 | Mipot S.p.a.
271 | Mirakonta s.l.
272 | Miromico AG
273 | Mobile Mark, Inc.
274 | Motorola Solutions Inc.
275 | MTES Co.,Limited
276 | Mueller Systems
277 | Multi-Tech Systems, Inc
278 | Multimedia Development   Corporation (Mdec)
279 | MURATA ELECTRONICS EUROPE BV
280 | myDevices
281 | Myfox SAS
282 | Nable communications
283 | National Narrowband Network   Communication
284 | National Taiwan University of   Science and Technology
285 | NEC Corporation
286 | Nemeus
287 | Neptune Technology Group, Inc.
288 | netLiNK Controls
289 | Netvox Technology Co., Ltd.
290 | Netzikon GmbH
291 | New H3C Technologies Co., Ltd.
292 | Next Field Co., Ltd.
293 | nFore Technology Co., Ltd
294 | NiceRF Wireless Technology Co.,   Ltd
295 | Nippon Telephone and Telegraph
296 | NKE WATTECO
297 | Northern Mechatronics Inc.
298 | Nsoft India ServicesPvt Ltd
299 | Occammd
300 | OCEASOFT
301 | Octotech Inc.
302 | OGERO Telecom
303 | Oi Electric Company Ltd.
304 | Oki Electric Industry Co., Ltd.
305 | Omani Qatari Telecommunications   Company
306 | Omniimpex GmbH
307 | Onethinx B.V.
308 | ORANGE
309 | OrbiWise
310 | Oresundskraft AB
311 | ORION (Ontario Research &   Innovation Optical Network)
312 | Orion System LLP
313 | OXON AG
314 | PacketWorx Inc.
315 | Parametric Engineering GmbH
316 | Pessl Instruments GmbH
317 | PFK Electronics
318 | Piraeus University of Applied   Science
319 | Plintron Mobility Solutions   Private LTD
320 | PLNetworks, Inc.
321 | Portwell, Inc
322 | Post CH AG
323 | ProEsys Srl
324 | Protonex LLC dba PNI Sensor
325 | Proximus SA
326 | PSY Engineering College
327 | PUC-Rio
328 | Pulse LARSEN Antennas
329 | Pycom
330 | PYRESCOM SAS
331 | QMC (Quadlogic Meters Canada   Inc.)
332 | Quanto AG
333 | R3 Nextgen Solution Sdn Bhd
334 | Radio Bridge Inc
335 | Rakon Limited
336 | Ranger Systems Co., Ltd.
337 | Raycap
338 | RedwoodComm Co., Ltd.
339 | Regent University
340 | Remote Solution Co., Ltd.
341 | REQUEA
342 | RF Solutions Ltd
343 | RMIT University
344 | Robeau Ltd.
345 | Rocky Mountain Equipment
346 | Rohde & Schwarz GmbH &   Co KG
347 | RTX A/S
348 | Ruckus Wireless, Inc
349 | Ruijie Networks Co., Ltd
350 | RuiXingHengFang   Network(Shenzhen) Co.,ltd
351 | Runtime
352 | Ryoden Corporation
353 | SAGEMCOM BROADBAND SAS
354 | SAMSON KT-Elektronik
355 | Sanmina Corporation
356 | Schneider Electric
357 | School of Information &   Electrical Engineering of Hebei University of Engineering, China
358 | SEAS-NVE
359 | Security Platform Inc.
360 | Sehaj Synergy Technologies   Private Limited
361 | Seiryo Electric Corporation
362 | Semtech
363 | Senet, Inc.
364 | SenRa Tech Pvt. Ltd.
365 | Sense For Innovation BV
366 | SenseWay, Inc.
367 | SENSING LABS
368 | Sensoterra
369 | Sercomm Corp
370 | SGS Group
371 | Shanghai Holystar Information   Technology
372 | Shenzhen Friendcom Technology   Development
373 | Shenzhen Winext Technology Co   Ltd
374 | Witlink Co., Ltd.
375 | Shinko Shoji Co., Ltd.
376 | Signify Netherlands B.V.
377 | Silicon Controls
378 | SIRADEL
379 | SITRI Innovations
380 | SK Telecom
381 | SK Telesys
382 | Skyhook Wireless, Inc
383 | Skysens Teknoloji A.S. (   SKYSENS)
384 | Slovanet a.s.
385 | SMARTHOME FRANCE
386 | SmartMakers GmbH
387 | SMK Corporation
388 | SoftBank Corp.
389 | SOLiD Inc.
390 | SORACOM INC.
391 | Spark New Zealand Trading   Limited
392 | SparkLAN Communications Inc.
393 | SQRL Solutions UG
394 | SRETT
395 | STACKFORCE GmbH
396 | StarHub Limited
397 | STIMIO
398 | STMicroelectronics International   NV
399 | Stream Technologies
400 | StreamLine - AAN BV
401 | STREGA SPRL
402 | Sungkyunkwan University, Media   System Lab
403 | Swiss Innovation Lab
404 | Swisscom (Switzerland) Ltd
405 | Switch Science, Inc.
406 | Syrinx Industrial Electronics   b.v.
407 | SYSDEV Srl
408 | Taggle Systems
409 | TalkPool AB
410 | TDK Corporation
411 | Tech Mahindra Ltd
412 | Tech4Race
413 | Tehama Wireless Design Group
414 | Tekelek
415 | TEKTELIC Communications Inc.
416 | Telecommunications Circuits Lab,   EPFL
417 | Telecommunications Technology   Association
418 | Telemar spa
419 | Telematics Wireless
420 | Telent GmbH
421 | Telit Communications S.p.A
422 | Telog Instruments, Inc.
423 | Teltronic AG
424 | Temperature@lert
425 | Tenna, LLC
426 | TEOCO Corporation
427 | Terranova Srl
428 | The Things Network Foundation
429 | theMakers.org
430 | Thingenix LLC
431 | Thuraya Telecommunications
432 | TrackNet
433 | Traqueur
434 | Trinity College Dublin
435 | TRUSTED OBJECTS S.A.S
436 | Turbo Technologies Corporation
437 | TUV Rheinland Group
438 | Ulster University
439 | UNIDATA SPA
440 | Unitec Semicondutores SA
441 | Universidad Autonoma de   Zacatecas
442 | Universitat Oberta de Catalunya
443 | University of Calgary
444 | University of Cape Town
445 | University of New Hampshire   InterOperability Laboratory (UNH-IOL)
446 | University of Saskatchewan
447 | University of Wollongong
448 | Urbana Smart Solutions Pte Ltd
449 | Urmet TLC
450 | UTFSM- CCTval Research Lab
451 | Ventia Utility Services Pty Ltd
452 | Verisure Innovaion AB
453 | Viloc
454 | Vision Metering, LLC
455 | Vision Valley
456 | VOLANSYS TECHNOLOGIES PVT. LTD.
457 | WaterBit, Inc.
458 | Webdyn
459 | Wi6labs
460 | Wifx Sarl
461 | Wireless Research Center of   North Carolina
462 | Wireless String Ltd
463 | WISeKey Semiconductors
464 | Woodenshark
465 | Woodstream Corp
466 | Worldsensing S.L.
467 | Wyres SAS
468 | X-Telia Group inc.
469 | Xeelas
470 | Xiamen Four-Faith Communication   Technology Co., Ltd.
471 | XterConnect SAS
472 | Yasam Elektronik Sayaclari A.S.
473 | Yokogawa Electric Corporation
474 | Minol ZENNER Connect GmbH
475 | Zhongke SmartCity Electronic   Technology Co. , Ltd
476 | Ziut B.V.
477 | ZTE CORPORATION
478 | Riddle&Code
479 | Nationz Technologies Inc.
480 | VTC Digital Telecommunications   One Member Company Limited
481 | Google LLC
482 | Insight SIP SAS
483 | Nippon Signal Co., Ltd.
484 | Sensys
485 | Renesas Electronics Corporation
486 | Eastcompeace Technology Co.,   Ltd.
487 | Solvera Lynx
488 | Internet of Things America LLC
489 | Duracell US Operations, Inc
490 | 8power Limited
491 | Irexnet Co., Ltd
492 | Aartesys AG
493 | ACN Advanced Communications   Network SA
494 | Inria Saclay Ile de France   Research Centre
495 | Sensor Network Services GmbH
496 | Comicon Ltd
497 | NMG S.A.
498 | Allora Factory
499 | AAEON Technology Inc
500 | Cypress Semiconductor
501 | MTT OJSC
502 | Remedial Performance Pte Ltd
503 | NetOP IoT Network Operator EURO   B.V.
504 | Metova Inc.
505 | AcSiP Technology Corp
506 | Nebra Ltd
507 | Shenzhen Tencent Computer   Systems Company Limited
508 | Shanghai Sunray Technology Stock   Co., LTD
509 | UNICO Computer Systems PTY. LTD.
510 | Beijing Jingdong Shangke   Information Technology Co., LTD
511 | Telekom Srbija
512 | Solum Co., Ltd
513 | Research and Production Company   Incotex
514 | AN10, Inc.
515 | Lobaro GmbH
516 | Akenza AG
517 | VADS Berhad
518 | Flowserve Corporation
519 | Sauermann Group
520 | Inria Saclay-ile-de-France   Research Centre
521 | SENSONEO j.s.a
522 | Beijing Jingdong Shangke   Information Technology Co., Ltd. ("Beijing Shangke")
523 | Xelba
524 | Ubicquia, LLC
525 | HAZARDTECH Pty Ltd
526 | Rossma LTD
527 | Komro GmbH
528 | B Meters SRL
529 | AKCess Pro Ltd
530 | Kama-contract, LLC
531 | SCHREDER SA
532 | Neosen Energy LLC
533 | NEPTUNE Information Technologies   GmbH
534 | Richardson RFPD
535 | Wickedride Adventure Services   Pvt Ltd
536 | ASR Microelectronics (Shanghai)   Co., Ltd.
537 | Andorra Telecom SAU
538 | China Academy of Information   Communications Technology
539 | CyberEye Research Labs &   Security Solutions Pvt. Ltd.
540 | ResIOT Ublsoftware Srl
541 | Syncrasy Limited
542 | NEXTRONIC
543 | G2 Misuratori SRL
544 | Sainte-Lizaigne
545 | Shanghai Zhongyi Industrial   Control Co.,LTD
546 | Informed Decisions PTY LTD
547 | DTU Fotonik
548 | Arthur D Riley & Co Ltd
549 | Watty Corporation
550 | The University of Tokyo
551 | Vantron Technology Inc
552 | Richer Link Technologies Co.,Ltd
553 | Social Area Networks Co., Ltd.
554 | Iotix AS
555 | Nordic Automation Systems
556 | OPTAGE Inc
557 | Umpi srl
558 | Bharat Institute of Engg + Tech
559 | Skiply SAS
560 | Instituto Brasilia De Tecnologia   E Inovacao
561 | Asociatia Pentru Dezvoltare Si   Mediu
562 | 2direct Asia Ltd.
563 | Africa Connect
564 | eSenseLab Ltd.
565 | Ueda Japan Radio Co., Ltd.
566 | SmartRent
567 | Smart Parks
568 | CareBand, Inc
569 | Target Corporation
570 | RAKwireless Technology Co.
571 | ThingPark China
572 | sigrenEa SAS
573 | Open Sensors
574 | Elvaco AB
575 | Ajiozi Limited
576 | Xavier School of Management
577 | International Centre for Free   and Open Source Software (ICFOSS)
578 | DTU Fotonik OLD
579 | OpenIOT
580 | Nanjing University of Science   and Technology
581 | Institut Mines-Telecom IMT
582 | West Electronic &   Applications Network
583 | Federal University of Technology   Campus Apucarana
584 | Universidad Politecnica de   Cartagena
585 | CM Systems LLC
586 | Colony 5 Chicago
587 | Good Will Instrument Co., Ltd.   (GWINSTEK)
588 | CoxCom, LLC d/b/a Cox2M
589 | VT iDirect, Inc.
590 | Alpha-Omega Technology GmbH   & Co.KG
591 | Fiber Misr
592 | VIA University College, Campus   Horsens
593 | Intellienergy Tech SRL
594 | Swarm Technologies, Inc.
595 | ST Electronics (Info-Comm   Systems) Pte. Ltd.
596 | Hunan She Yun Electronic   Technology co. Ltd
597 | ZTACOM Co., Ltd.
598 | Boston Networks Limited
599 | Redexia Network S.L.
600 | Cahors Group
601 | Ursalink Technology Co., Ltd.
602 | DataAlliance Inc.
603 | Carlo Gavazzi Controls S.p.A.
604 | Cavagna Group SPA
605 | JSC Axioma Metering
606 | Viaanix
607 | Ellenex Pty Ltd
608 | TATA Communications
609 | Sontex SA
610 | University Grenoble Alpes
611 | Holy Cross of Davao
612 | Nerospec
613 | Browan Communication Incorp.
614 | Capita Business Services Limited
615 | ZXCLAA Technology Co.Ltd.
616 | Maxtrack Industrial Ltda
617 | Airconn Bel Technology
618 | Metis Secure Solutions
619 | Keysight Technologies
620 | Vodafone NRW GmbH
621 | Faststream Technologies
622 | ABB Switzerland Ltd
623 | Advangrid
624 | ITK IOT
625 | Sensative AB
626 | Beijing Commsat Technology   Development Co. Ltd.
627 | Hydrelis SAS
628 | Transmeet Ltda EPP
629 | Atombeam Technologies
630 | CoXlab Inc.
631 | Vertical M2M
632 | Telkom Indonesia
633 | Thingstream AG
634 | Dish Network
635 | Capgemini Nederland BV
636 | Universidade Federal de Santa   Maria UFSM
637 | China Electronics   Standardization Institute
638 | Barani Design Technologies,   s.r.o.
639 | ISA Co., Ltd.
640 | ASTEL JSC
641 | Shanghai Shuncom Smart   Technology Co., Ltd
642 | LINZ STROM GAS WARME GmbH fur   Energiedienstleistungen und Telekommunikation
643 | Seba Dynatronic Mess und   Ortungstechnik GmbH
644 | Nucleon e.V.
645 | Apator Miitors ApS
646 | Mesh-Net Ltd
647 | BICSI South Pacific
648 | MXC Foundation GmbH
649 | HTW Berlin
650 | Hong Kong Applied Science and   Technology Research Institute
651 | REACH Tech(Xiamen) Co.,Ltd.
652 | Teneo IoT
653 | Paige Wireless, LLC
654 | Siema Application
655 | Water Einstein, Inc.
656 | HouwaSystemDesign K.K.
657 | Goldcard Smart Group Co.,Ltd
658 | Mieloo & Alexander
659 | Yosensi Sp. z o.o.
660 | Netze BW GmbH
661 | Alliot Technologies Ltd
662 | Renau Corporation
663 | Avantix
664 | Polygravity Services GmbH
665 | Sensedge d.o.o.
666 | Chirp Technologies LLC
667 | Unterhalt Und Dienst Iberica   S.L.
668 | Syniverse Technologies
669 | BuildingLink.com
670 | Infomir SA
671 | Softhard.IO Limited
672 | Desarrollo de Infraestructura de   Telecomunicaciones Peru
673 | WEG Drives & Controls
674 | ConnectedFresh
675 | WIKA Alexander Wiegand SE &   Co. KG
676 | Dragino Technology Co., Limited
677 | Omni-ID
678 | AGRROBOT Company Limited
679 | Nesten, Inc.
680 | Bright Science
681 | Allegheny County Airport   Authority
682 | 4CG Cymru 2010 Ltd
683 | MLR Institute of Technology
684 | OXIT LLC
685 | EnerKey Oy
686 | NEXELEC
687 | Parsons
688 | PHOENIX CONTACT Electronics GmbH
689 | Contel Communications, Inc.
690 | TKF (Twentsche Babelfabriek)   B.V.
691 | IoT Ventures Ltd
692 | Arduino SA
693 | Marubun Corporation
694 | Universitas Narotama
695 | Small Data Garden Oy
696 | Internet of Things Ukraine
697 | Shenzhen Kaifa Technology Co.,   Ltd.
698 | eBZ GmbH
699 | Intracom S.A. Telecom Solutions
700 | HEIG-VD
701 | American Tower Do Brasil
702 | Terre des Hommes Foundation
703 | AMIT Wireless Inc.
704 | One Network Consulting Pvt. Ltd.
705 | Sensile Technologies SA
706 | Danalto Limited
707 | Aloxy
708 | IMBuildings B.V.
709 | Saft
710 | Mesura Metering Srl
711 | Universiti Kuala Lumpur (UniKL   MIIT)
712 | Towercom, a.s.
713 | Internet Initiative Japan Inc.
714 | AMAZON Web Services, Inc. (AWS)
715 | Alperia Fiber Srl
716 | Enless Wireless
717 | Indian Society for Remote   Engineering and Data Science
718 | Sichuan Changhong Network   Technologies Co.,Ltd.
719 | Cicor Group
720 | IHMPACIFIC
721 | Intel Corporation
722 | Symmetry Electronics
723 | Rubicon Systems Australia PTY   LTD
724 | Siterwell Electronics Co., Ltd
725 | Energomera
726 | Luxshare-ICT, Inc
727 | Interlink Electronics
728 | Unitron NV
729 | INSTECH, S.A.P.I. DE C.V.
730 | Kouten
731 | Indian Institute of Technology   Bombay
732 | Soluciones y Servicios   Integrales Telco SA de CV
733 | Afghan Wireless Communication   Company
734 | PrognostiX
735 | PrognostiX-Poultry
736 | Konnex Enterprises Inc.
737 | Hangzhou Watermeter Co., Ltd.
738 | Financiere de l'Ombre
739 | STEINEL Solutions AG
740 | Nokeval Oy
741 | Hawle Armaturen AG
742 | SSE Contracting Limted t/a   Mayflower Smart Control
743 | RSAWEB
744 | Seeed Technology Co., Ltd
745 | ICE Gateway GmbH
746 | Shenzhen HOPE Microelectronics   Co., Ltd
747 | Lysir ehf
748 | Kamstrup A/S
749 | Adafruit Industries
750 | Elvexys SA
751 | Devtech M2M Limited
752 | CUD Group
753 | First Snow Co., Ltd
754 | Evkalipt R
755 | Compsesa
756 | British Telecommunications Plc
757 | Deepsenxe International Ltd.
758 | LACROIX Group
759 | IoT Aonchip SL
760 | CYSEC SA
761 | InVue
762 | Hamnet Gauteng South
763 | Universidade Federal do Ceara   UFC - Campus Sobral
764 | DZG Metering GmbH
765 | Gold Information Technology   Group
766 | LUNA ELEKTRIK ELEKTRONIK SAN VE   TIC A.S.
767 | Perth IoT Network (PIoTCN)
768 | DIREXIOT
769 | Baumer Bourdon-Haenni
770 | Sensor Networks, Inc.
771 | UPLINK Network GmbH
772 | Connesi S.p.A.
773 | NALTEC, Inc.
774 | Vutiliti
775 | Chevron
776 | ZataFi Communications, LLC
777 | University of Surrey
778 | One Network
779 | PRiOT AG
780 | Alternative Energy Innovations   S.L.
781 | Borough Smart Ltd
782 | SG Wireless Limited
783 | Pepperl+Fuchs AG
784 | VEGA Grieshaber KG
785 | uTerminal AG
786 | Moko Technology Ltd
787 | talam, Auroville Centre for   Scientific Research Trust
788 | SOFTYSOFT
789 | Deeptrack S.L.U.
790 | DTDS Technology Pte Ltd
791 | Carnegie Mellon University
792 | American Farm School
793 | Danang International Institute   of Technology (DNIIT)
794 | DMI, LLC
795 | University of REIMS
796 | Heyliot
797 | Asystom
798 | Zenseio LLC
799 | SHARINGOS HOLDINGS LIMITED
800 | KS Technologies, LLC
801 | The CRD-HK Charity
802 | Glassdome, Inc.
803 | Coris Life Sciences Monitoring,   Inc.
804 | HT Micron Semicondutores S.A.
805 | Schleswig-Holstein Netz AG
806 | University of Wurzburg, Chair of   Communication Networks
807 | Instituto Tecnologico de   Hermosillo
808 | Institute of Theoretical and   Applied Informatics, Polish Academy of Sciences
809 | Veea Inc.
810 | Urbit Group LLC
811 | mhascaro GmbH
812 | Maspro Denkoh Corp.
813 | Webee Corporation
814 | ELA Innovation

This list is subject to change, but the vendor IDs are static and will not get reallocated to a new member.

**Comment by laurensslats** [comment]
@johanstokking where did you get this VendorID list from? Is this from the LoRa Alliance?

**Comment by johanstokking** [comment]
Yes, this is from the LoRa Alliance

**Comment by laurensslats** [comment]
Any updates on the review?
