### ISSUE TITLE
Tektelic Sensor Rename and Agri decoder update issues

### ISSUE THREAD

**Issue by jammiemil** [TheThingsNetwork/lorawan-devices#504]
#### Summary
Due to the changes in #466 I've had to go through and update the Hardware info for all my deployed tektelic sensors as the previous model_id (t00059xx-agriculture-sensor) was no longer valid (Replaced with (t000598x-kiwi), Further to this however the same change has replaced the previous decoder with an incomplete decoder that no longer takes the frequency + Voltage values and calculated 'Watermark' Values, nor does it produce the temperature readings.

#### What do you see now?
(Taken from Comunity Edition):
"decoded_payload": {
        "input3_voltage": 238,
        "input4_voltage": 247,
        "input5_frequency": 2366,
        "input6_frequency": 49,
        "light_intensity": 7912,
        "port": "10",
        "raw": "[03, 02, 00, EE, 04, 02, 00, F7, 05, 04, 09, 3E, 06, 04, 00, 31, 09, 65, 1E, E8]"
      },

#### What do you want to see instead?
(Taken from a private TTS Deployment using the old version):

"decoded_payload": {
        "adj_watermark1": 35.83154248394849,
        "adj_watermark2": 35.310370381295236,
        "input3_voltage": 396,
        "input4_voltage": 399,
        "input5_frequency": 1475,
        "input6_frequency": 2033,
        "light_intensity": 2705,
        "port": "10",
        "raw": "[03, 02, 01, 8C, 04, 02, 01, 8F, 05, 04, 05, C3, 06, 04, 07, F1, 09, 65, 0A, 91]",
        "temperature1": 22.084001808306795,
        "temperature2": 21.842793116199942
      },

#### How do you propose to implement this?
Decoder should be reverted/Updated with missing functions, Ideally the previous model_id should also be reinstated so that others in this position can still access the decoder

#### Can you do this yourself and submit a Pull Request?
No, I believe @JBischoff1 Looks at These

**Comment by JBischoff1** [comment]
@jammiemil Thank you for raising this issue. I have created a pull request (#505) to address this. I modified the decoder to include the functions for calculating the watermark and temperature values. I also reverted the model ID back to the previous one.

**Comment by jammiemil** [comment]
Thanks @JBischoff1 , I saw this go into the release that pushed to cloud today so ive checked it out.

Looks like the name was changed to t00059xx-kiwi rather than reverting to t00059xx-agriculture-sensor so ive updated my devices again (Thankfully i had the script prepared this time), I can now see the right metrics being decoded at least. 👍
