### ISSUE TITLE
Where to get validate-image

### ISSUE THREAD

**Issue by dragino** [TheThingsNetwork/lorawan-devices#575]
npm run validate stops like below. 

sensedge: senstick-pure: EU863-870: payload codec senstick-pure-codec valid
sensecap: sensecaps2100-data-logger: EU863-870: payload codec sensecap2100-codec valid
sensecap: sensecaps2120-8-in-1: EU863-870: payload codec sensecap2120-8-in-1-codec valid
Error: Command failed: bin/validate-image ./vendor/mcci/catena4612.png
/bin/sh: bin/validate-image: No such file or directory

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'bin/validate-image ./vendor/mcci/catena4612.png'
}

**Comment by dragino** [comment]
This message block me to further do validate check for code. How to skip this?

**Comment by Jaime-Trinidad** [comment]
Hi, @dragino I switched to your branch, but I was not able to reply to this error, I run `make validate` and `make validate fmt` without any trouble, also the file exists, maybe your computer runs out of memory during the validation, we already modify `validate.js` file due these problems. Can you run it and sew if still happens with the same file and add the code lines.

**Comment by Jaime-Trinidad** [comment]
@dragino any update here?

**Comment by Jaime-Trinidad** [comment]
Try also running 
`./bin/validate-image "vendor/mcci/catena4612.png"`
If you have error please attach it.

**Comment by Jaime-Trinidad** [comment]
Multiple users were apparently experiencing issues with the `catena4612.png` image. We have since converted the format of the image to a .jpg file, and it seems that the error has ceased to occur. As a result, I will be closing this issue for now. However, please do not hesitate to reach out if you encounter any further problems or if you believe that this issue needs to be reopened.
