### ISSUE TITLE
Add new deivce issue

### ISSUE THREAD

**Issue by Kway99** [TheThingsNetwork/lorawan-devices#579]
#### Summary

The pull request has been approved, the commit was merged into the master.
https://github.com/TheThingsNetwork/lorawan-devices/pull/560
But I can't see the added device on the device register page.
Can someone tell me the reason? Thanks!
#### What do you see now?

<img width="604" alt="image" src="https://user-images.githubusercontent.com/108512334/212029070-85fc5615-3b14-4b1d-b849-5e1500029161.png">

#### What do you want to see instead?

See the added S2120-8-in-1 device.

#### How do you propose to implement this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by NicolasMrad** [comment]
I was able to find the S2120-8-in-1 device, as you can notice in the attached screenshot. It's the last device model in the SenseCap Device Brand.

<img width="832" alt="image" src="https://user-images.githubusercontent.com/87186070/212851724-ff735bf8-a514-48f8-8b9d-d59a6e685f37.png">

**Comment by Jaime-Trinidad** [comment]
Hi @Kway99 as Nicolas mentioned I also can see it in the console, the device is already in the console, when devices are merged they do not deploy automatically, they are in the console after the next version release of `TTS`. I will close the issue, please feel free to open it if you still continue with it.


<img width="472" alt="image" src="https://user-images.githubusercontent.com/81958808/212941820-0a532a1c-8cb0-47e2-aa66-13f967db855e.png">

**Comment by Kway99** [comment]
Thanks for your reply! I can also find it now~ thanks again!
