### ISSUE TITLE
BMETER HYDRODIGIT

### ISSUE THREAD

**Issue by IkerBA** [TheThingsNetwork/lorawan-devices#624]
#### Summary

VIF parameter wrongly detected for hectoliters, same value as liters.

#### What do you see now?

 //liters
    if (input.bytes[11] === 0x0D) {
      data.vif = input.bytes[11]*1;
    }
    //decaliters
    else if (input.bytes[11] === 0x0E){
      data.vif = input.bytes[11]*10;
    }
    //hectoliters
    else if(input.bytes[11] === 0x0D){
      data.vif = input.bytes[11]*100;

#### What do you want to see instead?

 //liters
    if (input.bytes[11] === 0x0D) {
      data.vif = input.bytes[11]*1;
    }
    //decaliters
    else if (input.bytes[11] === 0x0E){
      data.vif = input.bytes[11]*10;
    }
    //hectoliters
    else if(input.bytes[11] === 0x0F){
      data.vif = input.bytes[11]*100;

#### How do you propose to implement this?

Modify hectoliters detection

#### Can you do this yourself and submit a Pull Request?

No

**Comment by NicolasMrad** [comment]
@Jaime-Trinidad is this something you can check?

**Comment by IkerBA** [comment]
Data is sent as DEC numbers, not HEX so 2⁸ conversion is not right and must be picked decimals numbers as sent in the datagram.

**Comment by Jaime-Trinidad** [comment]
Decoder file is now fixed
