### ISSUE TITLE
Generic Node Payload Formatter update

### ISSUE THREAD

**Issue by azerimaker** [TheThingsNetwork/lorawan-devices#638]
#### Summary

Already existing Generic Node (SE) payload formatter is incomplete, since couple of month we added button state as well. Therefore it would be nice to have it updated. Please use the JS payload formatter below. 

#### Why do we need this?

Button states are now omitted from the decoded payload. 

#### What is already there? What do you see now?

[Existing ](https://github.com/TheThingsNetwork/lorawan-devices/blob/master/vendor/the-things-industries/generic-node-sensor-edition-codec.js)payload formatter is incomplete. 

#### What is missing? What do you want to see?

Updated payload formatter is also given in the [documentation](https://www.genericnode.com/docs/getting-started/platform-guide/). 
```
function decodeUplink(input) {
  var data = {};
  data.batt_volt = (input.bytes[0]/10);
  data.temperature = (((input.bytes[1] << 8) + input.bytes[2]) - 500)/10;
  data.humidity = ((input.bytes[3] << 8) + input.bytes[4])/10;
  data.button = input.bytes[5];

  return {
    data: data,
  };
}
```

#### Can you do this yourself and submit a Pull Request?

@Jaime-Trinidad please check.

**Comment by KrishnaIyer** [comment]
@Jaime-Trinidad: Please check if this update is needed.
