### ISSUE TITLE
Delay between merge of a pull request and availability of the decoders on the console

### ISSUE THREAD

**Issue by rflud** [TheThingsNetwork/lorawan-devices#679]
#### Summary
My merge request has been accepted 5 days ago and the decoders for our products are not updated on the console.

#### What do you see now?
On the console I can still see the previous decoders that are not available anymore in the master branch

#### What do you want to see instead?
I thought I would see right away the new decoders on the console. Is 5 days a normal delay or could it be an issue?

**Comment by KrishnaIyer** [comment]
The decoders are bundled with The Things Stack release assets. So new updates are only incorporated in the subsequent release.

If you are running your own version of The Things Stack, you can set the `--dr.assets-base-url` option and restart the stack to pick up new changes.

If you are using a hosted version, then you'll have to wait until the next update.

**Comment by rflud** [comment]
Thank you for the answer it's clear to me now.
