### ISSUE TITLE
Making codec private (non-visible) after submit to repository

### ISSUE THREAD

**Issue by mvujovic-vb** [TheThingsNetwork/lorawan-devices#685]
Hi, we would like to make our codec private in the submitting process if possible. I sent an email to Johan Stokking around 2 weeks ago but didn't get any response so far.

This is our preferred way to upload the decoder. If that's not possible we would update it in public mode.

Thank you in advance.

**Comment by KrishnaIyer** [comment]
By private do you mean that the codec shouldn't be visible in the repository or that only certain people should be allowed to use the codec?

**Comment by mvujovic-vb** [comment]
We would like that the source code of the codec isn't visible in the repository. Is that possible?

**Comment by KrishnaIyer** [comment]
Unfortunately, that's not possible since the contents of this repository is public.

**Comment by mvujovic-vb** [comment]
Thank you. We submitted our device in the following PR: https://github.com/TheThingsNetwork/lorawan-devices/pull/687
