### ISSUE TITLE
Add "particulate matter" (or "pm2.5") sensor

### ISSUE THREAD

**Issue by terrillmoore** [TheThingsNetwork/lorawan-devices#70]
#### Summary
Please add a suitable category for sensors that return particulate matter density in air (PM2.5, etc)

#### Why do we need this?
Particulate matter (particularly PM2.5) has health implications.

#### What is already there? What do you see now?

There is a dust category, but dust is measured differently than PM2.5, has different units (count/volume vs mass/volume), and is often binned differently.

#### How do you propose to implement this?
Not enough docs on how these categories are used to be sure. Might be easy, might be terribly difficult.

#### Can you do this yourself and submit a Pull Request?
Not right now.

**Comment by mikimite** [comment]
Did a pull request for this in their repo but still not aproved
https://github.com/lorawan-schema/draft-devices/pull/11

**Comment by johanstokking** [comment]
This is now merged, thanks guys!
