### ISSUE TITLE
Make validation

### ISSUE THREAD

**Issue by reghund1986** [TheThingsNetwork/lorawan-devices#709]
Hi Team ,

I am very new to TTN ,

Here we are created new vendor and added new sensor as per the document . here i am using vscode for editing the source code . 
after all , i am trying for "make validation" using vscode terminal but the response is make is not recognized .

Could you please help me to sort the issue.

**Comment by KrishnaIyer** [comment]
@LDannijs, could you please take a look?

**Comment by LDannijs** [comment]
Make sure you followed the Prerequisites: https://github.com/TheThingsNetwork/lorawan-devices#prerequisites
May i ask what Operating System you're using?

**Comment by LDannijs** [comment]
I'm pretty sure this can be closed since #715 user got make working, closing for now.
