### ISSUE TITLE
How to get updated device list in the console?

### ISSUE THREAD

**Issue by jeffallen** [TheThingsNetwork/lorawan-devices#711]
I see that the TrackerD is in this repo: https://github.com/TheThingsNetwork/lorawan-devices/blob/master/vendor/dragino/trackerd.yaml

But the TrackerD is not available for selection in the TTN console (https://eu1.cloud.thethings.network/)

How can I get an updated list?

**Comment by KrishnaIyer** [comment]
@LDannijs: Can you check and follow up?

**Comment by LDannijs** [comment]
I found the issue, Dragino's index file didn't have the sensor in there. Made a PR for it.

**Comment by LDannijs** [comment]
Issue got fixed in #712. Should be implemented in V3.28.2!
