### ISSUE TITLE
Error while validating 

### ISSUE THREAD

**Issue by reghund1986** [TheThingsNetwork/lorawan-devices#715]
HI ,

iam facing some issue while validating the code . 
"Error: Command failed: bin/validate-image ./vendor/adeunis/tic.png
'bin' is not recognized as an internal or external command,
operable program or batch file.
"
Are there any packages to be installed? 
Could you please help me to resolve the issue 
Regards
reghu
![TTN Bug](https://github.com/TheThingsNetwork/lorawan-devices/assets/114389968/ad729eb8-2329-4690-8264-cedde1e8d5d9)

#### Summary

...

#### What do you see now?

...

#### What do you want to see instead?

...

#### How do you propose to implement this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by KrishnaIyer** [comment]
@LDannijs, could you please take a look?

**Comment by reghund1986** [comment]
HI ,

Now I can validate the project without error . 

Is there any coding standard to be follow for .js . 
Am getting below error message.

 
![TTN Bug_1](https://github.com/TheThingsNetwork/lorawan-devices/assets/114389968/f8fbd6bc-ab6a-44ac-b842-bcbd26780513)

Hi , 

I tested the javascript manually , its giving proper output in json format .

{"data":{"id":109,"type":4,"seq_counter":19,"fw_version":1,"values":{"temperature":{"unit":"oc","value":22.9},"humidity":{"unit":"%","value":28.8}},"alarm_status":{"temperature":{"high":false,"low":false},"humidity":{"high":false,"low":true}},"states":{"battery":"100%","msg_type":"normal"}}}

Regards
Reghu

**Comment by LDannijs** [comment]
Hello @reghund1986, is this issue fixed? If so we can close it.

**Comment by reghund1986** [comment]
> Hello @reghund1986, is this issue fixed? If so we can close it.

Yes , its validating successfully .

**Comment by LDannijs** [comment]
Great to hear! Closing this issue.
