### ISSUE TITLE
Add field to provide hints about where to find firmware/hardware versions

### ISSUE THREAD

**Issue by kschiffer** [TheThingsNetwork/lorawan-devices#74]
#### Summary
When users select an end device they will need to know the firmware/hardware versions of the device. This information is oftentimes not easy to get. We should source some instructions that the manufacturer can provide which will help the user finding out the versions.

#### Why do we need this?
To improve device selection.

#### What is already there? What do you see now?
Nothing of that sort.

#### What is missing? What do you want to see?
A field somewhere in the device schema which can be used for such purposes.

#### How do you propose to implement this?
Trivial.

#### Can you do this yourself and submit a Pull Request?
Need some discussion on how to add this.

**Comment by johanstokking** [comment]
@benolayinka want to pick this up?

Way to implement would be to add a new string field to the end device object starting here: https://github.com/lorawan-schema/draft-devices/blob/master/schema.json#L705

**Comment by benolayinka** [comment]
I don't have permission to add reviewers @johanstokking https://github.com/lorawan-schema/draft-devices/pull/13

**Comment by johanstokking** [comment]
This is now reflected both in https://lorawan-schema.org/draft/devices/1/schema as well as the schema that is pulled in this repository. Please pull `master` to get the updated schema locally.

**Comment by benolayinka** [comment]
Closed by https://github.com/lorawan-schema/draft-devices/commit/4028c0a44da3a0276850f41275558c77275cf9c7

**Comment by benolayinka** [comment]
Reopened to allow @kschiffer to add some UX from the schema

**Comment by kschiffer** [comment]
The UX around this is already defined as part of TheThingsNetwork/lorawan-stack#3522.

I'll comment there that this is now available.
