### ISSUE TITLE
Generate devices csv

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-devices#745]
#### Summary

Can we generate a flat list of devices as a csv? We can then sync this to airtable

#### Why do we need this?

Sync data to airtable

#### What is already there? What do you see now?

Folder hierarchy

#### What is missing? What do you want to see?

name, vendor, description, image link, sensors, radios, height, width, length, weight, battery?, ip rating, urls, mac version?, rp version?, supports class b / class c?,

**Comment by johanstokking** [comment]
Most of this is quite straight forward and is readily available per end device.

The data model has a hierarchy:

- Vendor
  - Profile
  - End device
    - Hardware version
    - Firmware version (links to one or more supported hardware versions and a profile for each region)

The MAC version, RP version and LoRaWAN classes are in the profile. There may be differences between regions, and there can be devices with multiple firmware versions so we need to add some heuristics here.

For example, we could take the last firmware version and the first profile to determine these fields.

**Comment by LDannijs** [comment]
Iirc i wasn't able to change the labels before but i will remember it for next time.

**Comment by LDannijs** [comment]
PR #749 was merged, closing this.
