### ISSUE TITLE
Add Title option

### ISSUE THREAD

**Issue by EnlessWireless** [TheThingsNetwork/lorawan-devices#747]
#### Summary

Need to add the Title in the Transmitters. Unique title to be added for individual TX. Can we add new field in the yaml file (name , description , title), 
...

#### Why do we need this?

...

#### What is already there? What do you see now?

...

#### What is missing? What do you want to see?

...

#### How do you propose to implement this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by LDannijs** [comment]
Hello,

Does the `name` field not suffice? It is basically a title. If i am misunderstanding i apologize.

**Comment by EnlessWireless** [comment]
Hi Thanks for the quick response , Yes , we will use the name field to update the product title .
