### ISSUE TITLE
Feature request: please add suitable category for Modbus / Mbus / general purpose bridges

### ISSUE THREAD

**Issue by terrillmoore** [TheThingsNetwork/lorawan-devices#75]
#### Summary
Please add a suitable category for end-devices that incorporate general-purpose bridges to field busses such as Modbus, Mbus, RS485, I2C, and so forth. Perhaps generic "field bus"?

#### Why do we need this?
These devices (like the MCCI Catena 4801, 4802, 4470) access data that's available from other instrumentation. For someone searching for this kind of sensor, it's a distinct category.

#### What is already there? What do you see now?

There's not even a grab-bag "other" category. No way to categorize general purpose bridges.

#### How do you propose to implement this?
Not enough docs on how these categories are used to be sure. Might be easy, might be terribly difficult.

#### Can you do this yourself and submit a Pull Request?
Not right now.

**Comment by johanstokking** [comment]
Thanks @terrillmoore for your suggestion and apologies for the late follow up here.

I believe this is a great addition and it is in fact a small thing to do.

Instead of putting this under `sensors`, I think we need a separate field with interfaces with which the device can bridge.

Besides Modbus and M-Bus, is there anything else you can think of now? CAN bus?

**Comment by cBashTN** [comment]
We have [devices](https://download.keller-druck.com/api/download/VyyiKwTWpeTxLdpb9sSSK4/en/2021-01.pdf) with
- RS485  (works with a proprietary protocol)
- SDI-12 (for third-party multi-parameter sensors)
- analog interface (0..5 VDC)

**Comment by johanstokking** [comment]
@cBashTN cool, I added them to https://github.com/lorawan-schema/draft-devices/pull/16

I'm gonna merge that and update the schema dependency here, so you guys can start using this.

If there are more bridge interfaces, please file a follow up issue here or in that repository.
