### ISSUE TITLE
Dead reference for uplink payload schema domain inside schema.json

### ISSUE THREAD

**Issue by lonode** [TheThingsNetwork/lorawan-devices#759]
#### Summary
Inside _schema.json_,  `upLinkPayload` JSON Schema is not available, it points to a down domain :  https://schema.thethings.network/devicerepository/1/payload/schema#/definitions/uplinkPayload 

#### What do you want to see instead?
A valid schema.

#### How do you propose to implement this?
A "payload" schema is available inside the repo and located in `lib/payload.json`, is it the relevant schema ? It should be the one linked to.

**Comment by johanstokking** [comment]
@lonode the schema is not hosted, it is just a schema ID. You can find the latest version as `schema.json` in the repository root.
