### ISSUE TITLE
Missing Sensors on Devices

### ISSUE THREAD

**Issue by Jaime-Trinidad** [TheThingsNetwork/lorawan-devices#769]
#### Summary

There are 252 devices without sensors, it is needed to review if there is the need to add sensors that are not in `.yaml` file or contact device makers so they can add them. Also this will work for the dropdown menu

#### What do you see now?

252 devices without sensors in `.yaml` file

i.e. Elvaco `cmi4130.yaml` they deleted `sensors` 

#### What do you want to see instead?

Reduce the number of devices without this information
#### How do you propose to implement this?

...

#### Can you do this yourself and submit a Pull Request?

@LDannijs let's work on this.

**Comment by KrishnaIyer** [comment]
@LDannijs: Can you pick this up in May?

**Comment by LDannijs** [comment]
@KrishnaIyer its already finished > #772 Just waiting for a merge. I'll send Jaime a message.

**Comment by KrishnaIyer** [comment]
Awesome. Thanks.
