### ISSUE TITLE
Add payload field for simulating uplinks in Device Repo

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-devices#8]
#### Summary
For users to experience devices in the device repo (and Virtual LoRaWAN Wall of Fame), they need to be able to simulate device uplinks which are shown in the front-end of the device repo (which is the marketplace and/or Virtual LoRaWAN Wall of Fame)

#### Why do we need this?
Awesome feature, allowing users to experience the devices, without having physical access, nor having to make a financial investment.

#### What is already there? What do you see now?
Open issue Simulate uplink issue console - [#2234](https://github.com/TheThingsNetwork/lorawan-stack/issues/2234)
Open issue Simulate uplink issue cli - [#3144](https://github.com/TheThingsNetwork/lorawan-stack/issues/3144)

#### What is missing? What do you want to see?
Device makers need to include one, or multiple examples of a device's payload data to be used for simulating uplinks

#### How do you propose to implement this?
Add a new field in the `profile.yaml` file

#### Can you do this yourself and submit a Pull Request?
Yes, I can submit a PR. @johanstokking to review.

**Comment by laurensslats** [comment]
See: https://github.com/TheThingsNetwork/lorawan-devices/pull/7/commits/a85a6bde670c113671b6485e3f62da3ad94fa3ff

**Comment by johanstokking** [comment]
This is already implemented via `examples`, see for example https://github.com/TheThingsNetwork/lorawan-devices/blob/3df419e1ff73dd3255434b6c53039335630c7f23/vendor/bosch/tps110-0233.yaml#L13
