### ISSUE TITLE
Improve docs on how the Device Repository can be used by applications

### ISSUE THREAD

**Issue by lnlp** [TheThingsNetwork/lorawan-devices#99]
Please add/improve docs on how the Device Repository can be used by applications.

**Comment by benolayinka** [comment]
@lnlp do you mean how the device repository can be used by applications within The Things Stack, or by third party applications?

**Comment by lnlp** [comment]
> @lnlp do you mean how the device repository can be used by applications within The Things Stack, or by third party applications?

Sorry for my late response.
I meant LoRaWAN applications in general. At first I expected the repository to be some kind of central service with an API, but that is apperently not how it is used.

**Comment by johanstokking** [comment]
@lnlp I think this should be covered by https://www.thethingsindustries.com/docs and https://www.thethingsnetwork.org/docs. Please file issues in https://github.com/TheThingsIndustries/lorawan-stack-docs and https://github.com/TheThingsNetwork/docs respectively.
